# thread schema

# --- !Ups

CREATE TABLE THREAD (
    ID serial,
    TITLE varchar(120) NOT NULL,
    USER_ID int NOT NULL,
    CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE COMMENT (
    ID serial,
    THREAD_ID bigint NOT NULL,
    COMMENT TEXT NOT NULL,
    USER_NAME TEXT,
    CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE MEBER (
    ID serial,
    LOGIN_ID TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    NAME TEXT NOT NULL,
    CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

# --- !Downs

DROP TABLE THREAD;
DROP TABLE COMMENT;
DROP TABLE MEBER;