# thread schema

# --- !Ups

INSERT INTO THREAD (TITLE,USER_ID) values ('タイトル1',1);
INSERT INTO THREAD (TITLE,USER_ID) values ('タイトル2',1);

INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント1','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント2','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント3','おかだ');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント4','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント5','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント6','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント7','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント8','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント9','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント10','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント11','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント12','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント13','OKD');
INSERT INTO COMMENT (THREAD_ID,COMMENT,USER_NAME) VALUES (1,'コメント14','OKD');

INSERT INTO USER (LOGIN_ID,PASSWORD,NAME) VALUES ('okada','123','OKD');
INSERT INTO USER (LOGIN_ID,PASSWORD,NAME) VALUES ('okada2','123','おかだ');
# --- !Downs